const USER_TYPES = ["user", "admin"];

const REGISTERATION_METHOD = ["google", "traditional"];

const REGISTERATION_AGENT = ["mobile-app", "web-app", "unknown"];

const DEFAULT_REGISTERATION_METHOD = REGISTERATION_METHOD[0];

const DEFAULT_REGISTERATION_AGENT = REGISTERATION_AGENT[2];

module.exports = {
    USER_TYPES,
    REGISTERATION_METHOD,
    REGISTERATION_AGENT,
    DEFAULT_REGISTERATION_METHOD,
    DEFAULT_REGISTERATION_AGENT
}